### ISSUE TITLE
Interstitials ads load systematic fail 

### ISSUE THREAD

**Issue by mini-Niark** [merbin2012/cordova-plugin-codeplay-facebookads-free#10]
Hi,

I use your plugin in one of our App and it used to work just fine but now when I launch the app, I get this message :

	"E/GraphResponse: {HttpStatus: 400, errorCode: 100, subErrorCode: 33, errorType: GraphMethodException, errorMessage: Unsupported get request. Object with ID 'XXXXX999503XXXXX' does not exist, cannot be loaded due to missing permissions, or does not support this operation. Please read the Graph API documentation at https://developers.facebook.com/docs/graph-api}"

(The Id is the right one)

Then, every time I try to load an interstitial ad it fail with a different message depending on the device :
- "Facebook interstitial Ads failed to load: no fill" the first time then  "Facebook interstitial Ads failed to load: Ad was re-loaded too frequently" (there is a minimum of 40 seconds between every load) on emulator with API 28.
- "Facebook interstitial Ads failed to load: (#2) Service temporarily unavailable" on Huawai with API 26.

I noticed that with the new facebook-sdk 5.6.0 one of the function used by the plugin was deprecated but even by forcing facebook-sdk 5.5.0, it's still not working (but no more deprecated warning).

**Comment by merbin2012** [comment]
Did you try to load with testing flag?

**Comment by mini-Niark** [comment]
Yes, it didn't worked.

**Comment by merbin2012** [comment]
Everything is fixed in the latest version. Kindly check and reopen, if still present this error. Thank you
