### ISSUE TITLE
Native ads

### ISSUE THREAD

**Issue by RayBez** [merbin2012/cordova-plugin-codeplay-facebookads-free#11]
Is this plugin able to show native ads and if so, is there an example that I can look at?

**Comment by merbin2012** [comment]
Not now.

**Comment by vickytak** [comment]
If this plugin doesn't support native ads, than it is use less

**Comment by merbin2012** [comment]
Ok. Thank you

**Comment by bsikatti16** [comment]
Any plugin that supports native ads.
