### ISSUE TITLE
App crashes on hiding banner ads.

### ISSUE THREAD

**Issue by shree7655** [merbin2012/cordova-plugin-codeplay-facebookads-free#12]
App crashed when i call to **cordova.plugins.codeplayfacebookads.hideBannerAds("",success,fail);** function.
![Screenshot_2020-01-08-03-18-15-383_com miui bugreport](https://user-images.githubusercontent.com/52069988/71933034-32dfc480-31c7-11ea-8b59-94d57023fbcc.jpg)

**Comment by merbin2012** [comment]
Are you using the latest version?

**Comment by elkhalifte** [comment]
Yes the app will crash if you try to hide a banner add while the banner isn't loaded .

**Comment by merbin2012** [comment]
Thank you very much, this issue is fixed in version 0.1.6.
