### ISSUE TITLE
Ionic Example 

### ISSUE THREAD

**Issue by elkhalifte** [merbin2012/cordova-plugin-codeplay-facebookads-free#15]
Hello ,

Thanks for creating this plugin, 
Is there any working example to get it work on ionic.?

**Comment by salmank63** [comment]
Any update on this. I am also looking Facebook Ads integration in Ionic 5.

**Comment by merbin2012** [comment]
You can integrate, but I'm not using ionic so I can't help you. But I'm
sure you can use this on ionic.

**Comment by elkhalifte** [comment]
Yes. i have using this plugin in my ionic 5 app. its working perfectly

**Comment by salmank63** [comment]
@elkhalifte Thank You.

**Comment by ionic123** [comment]
@elkhalifte please can you help for integrate this plugin in ionic 5

**Comment by elkhalifte** [comment]
Contact me by mail : elkhalifteamerica@gmail.com 
Or WhatsApp: +212695381939
Maybe I will post an ionic example here on github . I just dont have time right now
