### ISSUE TITLE
integrate  cordova-plugin-codeplay-facebookads-free in ionic

### ISSUE THREAD

**Issue by ionic123** [merbin2012/cordova-plugin-codeplay-facebookads-free#19]
How i can integrate this plugin in ionic 5

**Comment by sansopheakh** [comment]
> How i can integrate this plugin in ionic 5

Yeah, It's working well. I'm using this plugin on Ionic4 and Ionic5.

**Comment by ucefe** [comment]
@sansopheakh can you explain more how with the same function cordova.xxxx. ?????

**Comment by merbin2012** [comment]
close due to no response.
