### ISSUE TITLE
More than one banner

### ISSUE THREAD

**Issue by Be4t5** [merbin2012/cordova-plugin-codeplay-facebookads-free#2]
When you call the function to create a banner multiple times, it continue to add banner instead of remove the current banner and recreating it. Could you please fix this?

**Comment by merbin2012** [comment]
Sorry for the late reply, this problem not affecting me. I will not call to show the banner multiple time. I am very busy with other work, so it takes more time to solve.

**Comment by Chamaraindrajith97** [comment]
> When you call the function to create a banner multiple times, it continue to add banner instead of remove the current banner and recreating it. Could you please fix this?

I faced this issue too. I found what is the problem of mine. Refreshing the page is the problem. If your app has the refreshing option, Before refreshing the page, call hide banner ad function. I think this might be helpful for someone. (If you are not facing that problem check you called show banner ad function twice by accidentally.)

**Comment by merbin2012** [comment]
Kindly check this, in the latest version this issue was fixed. Thank you.
