### ISSUE TITLE
showBannerAds No Fill msg error whith isTesting:true

### ISSUE THREAD

**Issue by catapulte2** [merbin2012/cordova-plugin-codeplay-facebookads-free#20]
Hi,

Thanks a lot for this plugin.
While testing with "isTesting = true", all is perfect and I can see the Facebook demo banner ads.
But when putting in production with is "Testing= false", all call ends with error : "No fill"
Does any body have find solution for this?

Many thanks in advance.

N.B  : All is ok in Facebook console

**Comment by catapulte2** [comment]
If it may help other, this message came when you don't have Facebook on your phone.... ;-)
Just install connect and in production (from PlayStore download) you will see ads.
Many thanks for this plugin and sorry for my stupid noise.

**Comment by merbin2012** [comment]
You are welcome
