### ISSUE TITLE
error: package admob.plus.cordova does not exist

### ISSUE THREAD

**Issue by diaxotora** [merbin2012/cordova-plugin-codeplay-facebookads-free#29]
Hi,
When I run the project I have this error:
error: package admob.plus.cordova does not exist
import admob.plus.cordova.Generated;
                          ^
1 error
And when I comment out the line: import admob.plus.cordova.Generated; in: codeplayfacebookads.java I don't have any more runtime error but the mediation doesn't work, do I have to install admob-plus-cordova because when I install it I have another error
Thanks for your help

**Comment by merbin2012** [comment]
If you want to use AdMob mediation, no need to use this plugin, you can use an AdMob plugin like (https://admob-plus.github.io/docs) and just import the following line into your grade file, then while you call AdMob banner, it will automatically trigger Facebook ads too, but you must configure properly.
`implementation 'com.google.ads.mediation:facebook:6.7.0.0'`

After that, you can test the Facebook and Admob ads by the following method
https://developers.google.com/admob/android/mediation-test-suite

**Comment by Carlosps** [comment]
Hi @merbin2012 

Have you achieved this Admob mediation following the steps you mentioned? Did it work on Android and iOS?
I also use the AdMob plus you mentioned.

**Comment by merbin2012** [comment]
Yes, sure. If you want to test the implementation just following the below link steps
https://developers.google.com/admob/android/mediation-test-suite

**Comment by Carlosps** [comment]
Great to know that, thank you.

I will do the steps you listed. 

I will also mention that in this discussion about [Mediation Support](https://github.com/admob-plus/admob-plus/discussions/269). I believe some people also do not know about that.

Thank you again.

**Comment by merbin2012** [comment]
Yeah, sure.
