### ISSUE TITLE
Is the plugin still working?

### ISSUE THREAD

**Issue by wheezyy** [merbin2012/cordova-plugin-codeplay-facebookads-free#30]
I am getting ads request but no impression. I have updated settings to bidding at FAN portal.
Will updating the plugin fix.

Currently using: 
"cordova-plugin-codeplay-facebookads-free": "0.0.5",
ionic: v3

**Comment by merbin2012** [comment]
Is the test ad working?

**Comment by MightyFake** [comment]
I have the same problem (Using cordova9.0.0)
- Test Ads are working fine
- Getting ad requests but no impression
- Error on build asking for admob plus plugin

**Comment by elkhalifte** [comment]
facebook audience network is currently only supports bidding , so the plugin will not work , facebook audience network will inform you about this inside facebook audience network dashboard.

it is important to move your apps into bidding using admob or other mediation platforms.


+ [](https://developers.facebook.com/docs/audience-network/overview/in-house-mediation/server-to-server/)
facebook is working on its own mediation platform, that means this plugin may come back to life after facebook released its FAN mediation sdk to public.

**Comment by merbin2012** [comment]
@elkhalifte you are wrong, to change the bidding, you have to change some changes in your Facebook audience network only, not in FAN SDK.

**Comment by merbin2012** [comment]
@MightyFake Sorry for the late fix, kindly checks now. The error is fixed (Ver 0.2.0).

**Comment by MightyFake** [comment]
> @MightyFake Sorry for the late fix, kindly checks now. The error is fixed (Ver 0.2.0).

Okay thanks. The build error is fixed, but still no impression

**Comment by elkhalifte** [comment]
> @elkhalifte you are wrong, to change the bidding, you have to change some changes in your Facebook audience network only, not in FAN SDK.

native code will also need updates to work with other bidding networks
