### ISSUE TITLE
Getting Ad requests but no Impression> @MightyFake Sorry for the late fix, kindly checks now. The error is fixed (Ver 0.2.0).

### ISSUE THREAD

**Issue by MightyFake** [merbin2012/cordova-plugin-codeplay-facebookads-free#32]
> @MightyFake Sorry for the late fix, kindly checks now. The error is fixed (Ver 0.2.0).

Okay thanks. The build error is fixed, but still no impression

_Originally posted by @MightyFake in https://github.com/merbin2012/cordova-plugin-codeplay-facebookads-free/issues/30#issuecomment-960610651_

**Comment by merbin2012** [comment]
@MightyFake may I know, how many installs are you getting a day? I am getting as usual traffic.

**Comment by MightyFake** [comment]
50 with the last app where i used the plugin

**Comment by MightyFake** [comment]
Remade the app with all plugins. After a longer period of Google verification, now everything is working fine!
