### ISSUE TITLE
ionic 3 refusing to build

### ISSUE THREAD

**Issue by wheezyy** [merbin2012/cordova-plugin-codeplay-facebookads-free#5]
Tried creating a blank ionic App and add Facebookads plugin and its refusing to build.
ionic v3
cordova 8

cli packages: (/usr/lib/node_modules)

    @ionic/cli-utils  : 1.9.2
    ionic (Ionic CLI) : 3.9.2

global packages:

    Cordova CLI : 8.1.2 (cordova-lib@8.1.1) 

local packages:

    @ionic/app-scripts : 3.1.0
    Cordova Platforms  : android 7.0.0
    Ionic Framework    : ionic-angular 3.9.2

System:

    Android SDK Tools : 26.1.1
    Node              : v10.16.3
    npm               : 6.9.0 
    OS                : Linux 4.15

Error:
        FAILURE: Build failed with an exception.
        
        * What went wrong:
        Execution failed for task 
        ':app:transformDexArchiveWithExternalLibsDexMergerForDebug'.
        > java.lang.RuntimeException: java.lang.RuntimeException: 
        com.android.builder.dexing.DexArchiveMergerException: Unable to merge dex
        
        * Try:
        Run with --stacktrace option to get the stack trace. Run with --info or 
        --debug option to get more log output.
        
        * Get more help at https://help.gradle.org
        
        BUILD FAILED in 55s
        38 actionable tasks: 38 executed
        /home/willy/Desktop/workspace/adstest/platforms/android/gradlew: Command 
        failed with exit code 1 Error output:
        Note: Some input files use or override a deprecated API.
        Note: Recompile with -Xlint:deprecation for details.
        Note: Some input files use or override a deprecated API.
        Note: Recompile with -Xlint:deprecation for details.
        
        FAILURE: Build failed with an exception.
        
        * What went wrong:
        Execution failed for task 
        ':app:transformDexArchiveWithExternalLibsDexMergerForDebug'.
        > java.lang.RuntimeException: java.lang.RuntimeException: 
        com.android.builder.dexing.DexArchiveMergerException: Unable to merge dex
        
        * Try:
        Run with --stacktrace option to get the stack trace. Run with --info or 
        --debug option to get more log output.
        
        * Get more help at https://help.gradle.org
        
        BUILD FAILED in 55s

**Comment by merbin2012** [comment]
@wheezyy  Check your other plugin, some other plugin version is conflicting.

**Comment by wheezyy** [comment]
> @wheezyy Check your other plugin, some other plugin version is conflicting.

Its a blank project.. Just created new project and added the plugin the build.
