### ISSUE TITLE
Cannot read property

### ISSUE THREAD

**Issue by leonardop21** [merbin2012/cordova-plugin-codeplay-facebookads-free#9]
After installing the plugin and building the application, I get the error below in the console. Regardless of the ad I have to show

Uncaught TypeError: Cannot read property 'codeplayfacebookads' of undefined

![Captura de Tela 2019-12-10 às 15 23 27](https://user-images.githubusercontent.com/17708447/70557174-11a49d80-1b61-11ea-80dc-9d376c486e89.png)

I tried to apply to app.js and index.html

var options={
bannerid:"523519301434xxx_xxxxxxxxxxxxxxx"
,isTesting:true
};

cordova.plugins.codeplayfacebookads.showBannerAds(options,success,fail);

function success(result)
{
 console.log(result);
}
function fail(result)
{
 console.log(result);
}

**Comment by merbin2012** [comment]
Plugin doesn't properly installed. Plz check it.
